### PR TITLE
Model 2 stripe integration

### PR DESCRIPTION
**Pull request by zpolwrek**
Adds Stripe Functionality in the backend for user registration.

Added a charge amount verification support to backend. This has an added webserver request that I added for testing and should be checked by the Webserver team.

Modified the frontend post request in Setup.js to match the required Stripe information for the backend.

Modified the frontend Stripe public key to match the private key. This key pair is currently linked with my Stripe account. We can move this to a shared stripe account if needed.

Added the addition of points when a user makes a post. I realize that this should no be added through the Stripe branch. I was testing how to add it and forgot I was in the Stripe branch. Feel free to delete this code (veiws.py-> PostViewSet, CommentViewSet -> def create).

### CODE REVIEW

**Review by wkhammond — CHANGES_REQUESTED** [review]
This is a very large pull request. This needs in-class review, because code here affects every single team. Make sure each team writes off on this before merging, because we don't want to alter any code they've written this close to Demo or Die if we aren't positive it won't break everything.

**Comment by kgill55** [comment]
I haven't looked at any of this yet either, but is definitely too big to merge without everyone testing and looking at it. It looks like it will effect most teams. A better process for doing this is continuous smaller commits over a longer period of time. Adding this much in so close to the demo is unrealistic, the site could break and we would have little to no idea on how to troubleshoot the issue.

**Comment by zpolwrek** [comment]
Today I went over the front end changes I have made with Varun and the back end changes with Jackson so I think we are good on that front.

Just to clear up some things, the commits I made look much bigger than they actually are. What you see happening here is that I forgot to turn off my format code on save option for Javascript in my text editor. I remembered it for Python but when I made a small change to the front-ends js file, it saved and auto-formatted the entire document. This means those few hundred commits should actually be me changing 2 lines. (For note it was changing the public API key to match with the backend private API key as well as changing the stripe token that was sent). I am not good enough at Github to know if there is an easy way for me to fix that but if the front end is fine with how the format has changed for setup.js then I think we should leave it.

For the rest of the commits, a large majority of it is just adding our Stripe class and unit tests to the project. The number of code changes that are involved in integration to the backend are relatively small and I have shown Jackson that they have worked and that the payment_processor.py code unit tests all passed. The changes to model.py are all additions so it should not break anyone else's code unless there are issues with how the generated migration scripts work.

If there are any questions, concerns, or if you want to see the code work for yourself I'll gladly discuss that at tomorrow's team meeting.

**Review by wkhammond — COMMENTED** [review]
Thank you for the explanation. Looks good to me!

**Review by wkhammond — APPROVED** [review]

**Pull request merged**
