### PR TITLE
Potential fix for Login Token bug

### PR DESCRIPTION
**Pull request by zpolwrek**
I think I fixed the bug that forces us to use a private browser for logging in. Would love a review and some rigorous testing on the Heroku version.

Edit: we should still use a private browser for the demo both to be safe and to fix the other caching issues.

### CODE REVIEW

**Comment by JacksonWeber** [comment]
I'm nervous to accept this because of the comment on line 46 of the original. I'll see what Nick thinks though.

**Comment by zpolwrek** [comment]
That was my comment/code.

Edit: As long as it directs us to both homefeed / verification we should be good.

**Review by JacksonWeber — APPROVED** [review]
Let's give it the ole' college try!

**Comment by zpolwrek** [comment]
So I am still getting it sometimes (after clearing cookies it's fine), but I think it is happening a lot less.

**Pull request merged**
